name: Coordinator Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

concurrency:
  group: coordinator-pull-request-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pull-request-coordinator:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets: inherit
    with:
      charm-path: coordinator
