name: Auto-update coordinator Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

concurrency:
  group: coordinator-update-libs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-lib-coordinator:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v1
    secrets: inherit
    with:
      charm-path: coordinator