name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday

jobs:
    tics:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@775a6d71c22da5ea8acc57d5874a2abc35babd33 # v1
        secrets: inherit
