name: Worker Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

jobs:
  pull-request-worker:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v1
    secrets: inherit
    with:
      charm-path: worker
    concurrency:
      group: coordinator-pull-request-${{ github.ref }}